version: '3.9'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  web-api:
    build: ./web-API
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

  dotnet-app:
    build: ./dotnet-app
    ports:
      - "8080:8080"
    depends_on:
      - web-api

volumes:
  ollama_data: